kind: pipeline
name: default

steps:
- name: push-private-registry
  image: plugins/docker
  settings:
    repo: registry-castor.max-heidinger.de/simple-diff
    registry: registry-castor.max-heidinger.de
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: push-public-registry
  image: plugins/docker
  settings:
    repo: ghcr.io/mheidinger/simple-diff
    registry: ghcr.io
    tags:
      - latest
      - ci-${DRONE_BUILD_NUMBER}
    username:
      from_secret: github_username
    password:
      from_secret: github_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request

- name: update-deployment
  image: plugins/webhook
  settings:
    urls: https://portainer-castor.max-heidinger.de/api/webhooks/93d0565f-6f3a-4c27-9d2f-8ca7278b79b9
    username:
      from_secret: tac_username
    password:
      from_secret: tac_password
  when:
    branch:
    - master
    event:
      exclude:
      - pull_request
